# Generated by Django 3.1.5 on 2021-03-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(max_length=2000, verbose_name='URL')),
                ('entry_hash', models.CharField(max_length=64)),
                ('url_hash', models.CharField(max_length=64)),
                ('tiny_url', models.CharField(blank=True, max_length=10)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
